// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  event_feature: dynamic(() => import("./EventFeature")),
  event_list: dynamic(() => import("./EventList")),
  hero: dynamic(() => import("./Hero")),
  scroll_text: dynamic(() => import("./ScrollText")),
  universe_events: dynamic(() => import("./UniverseEvents")),
  universe_gallery: dynamic(() => import("./UniverseGallery")),
  universe_hero: dynamic(() => import("./UniverseHero")),
  universe_list: dynamic(() => import("./UniverseList")),
  universe_story: dynamic(() => import("./UniverseStory")),
  video: dynamic(() => import("./Video")),
};